---
- name: Configure AAP for Terraform Actions
  hosts: localhost
  tasks:
    - name: Create API Token so that EDA can call Controller
      ansible.platform.token:
        description: 'EDA Token'
        scope: "write"
        state: "present"
      register: aap_token
    - name: Create EDA credential for controller
      ansible.eda.credential:
        name: 'TF Actions EDA Credential'
        credential_type_name: 'Red Hat Ansible Automation Platform'
        organization_name: 'Default'
        inputs:
          host: 'http://myaap/api/controller'
          oauth_token: '{{ ansible_facts.aap_token.token }}'
    - name: Create EDA credential for event stream
      ansible.eda.credential:
        name: 'TF Actions Basic Event Stream Credential'
        credential_type_name: 'Basic Event Stream'
        organization_name: 'Default'
        inputs:
          username: 'tf-user'
          password: 'terrible'
    - name: Create EDA Project
      ansible.eda.project:
        name: 'TF Actions Project'
        organization_name: 'Default'
        url: 'https://github.com/dleehr/rulebooks-sandbox.git'
    - name: Create EDA Event Stream
      ansible.eda.event_stream:
        name: 'TF Actions Event Stream'
        credential_name: 'TF Actions Basic Event Stream Credential'
        organization_name: 'Default'
    - name: Create EDA Decision Environment
      ansible.eda.decision_environment:
        name: 'TF Actions Decision Environment'
        image_url: 'quay.io/ansible/ansible-rulebook:latest'
        organization_name: 'Default'
    - name: Create EDA Rulebook Activation
      ansible.eda.rulebook_activation:
        name: 'TF Actions Rulebook Activation'
        project_name: 'TF Actions Project'
        rulebook_name: 'tf-action-rulebook.yml'
        eda_credentials:
          - 'TF Actions EDA Credential'
        swap_single_source: true
        decision_environment_name: 'TF Actions Decision Environment'
        organization_name: 'Default'
    - name: Fetch Event Stream
      ansible.eda.event_stream_info:
        name: 'TF Actions Event Stream'
      register: event_stream
    - name: Show URL
      ansible.builtin.debug:
        msg: 'url {{ event_stream.event_streams[0].url }}'
